services:

  spring-boot-admin-dashboard-db:
    image: mysql:8.0.27
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MS_PASSWORD}
      MYSQL_DATABASE: ${DB_MS_SCHEMA_NAME}
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 20s
      timeout: 10s
      retries: 10

  spring-boot-admin-dashboard:
    image: spring-boot-admin-dashboard:0.0.1
    container_name: admin-dashboard-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_MS_PASSWORD: ${DB_MS_PASSWORD}
      DB_MS_USERNAME: ${DB_MS_USERNAME}
      DB_MS_SCHEMA_NAME: ${DB_MS_SCHEMA_NAME}
      SPRING_DATASOURCE_URL: jdbc:mysql://spring-boot-admin-dashboard-db:3306/${DB_MS_SCHEMA_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_MS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_MS_PASSWORD}
      MAIN_ADM_FIRSTNAME: ${MAIN_ADM_FIRSTNAME}
      MAIN_ADM_LASTNAME: ${MAIN_ADM_LASTNAME}
      MAIN_ADM_EMAIL: ${MAIN_ADM_EMAIL}
      MAIN_ADM_PASSWORD: ${MAIN_ADM_PASSWORD}
      MAIN_ADM_AGE: ${MAIN_ADM_AGE}
    ports:
      - "8088:8089"
    depends_on:
      spring-boot-admin-dashboard-db:
        condition: service_healthy
    restart: on-failure