# App properties
server.port=8089

# Logging
logging.level.org.springframework.web=DEBUG

# Jpa & Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Admin properties initialize
admin.first_name=${MAIN_ADM_FIRSTNAME:admin}
admin.last_name=${MAIN_ADM_LASTNAME:admin}
admin.email=${MAIN_ADM_EMAIL:admin@mail.com}
admin.password=${MAIN_ADM_PASSWORD:1234}
admin.age=${MAIN_ADM_AGE:18}

# Thymeleaf settings
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
